spring:
  profiles:
    active: local
server:
  port: ${PORT:8080}
---
spring:
  profiles: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    user: sa
    password:
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

---
spring:
  profiles: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${databaseUrl}
    username: ${usernameDB}
    password: ${passwordDB}
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    url: ${databaseUrl}
    user: ${usernameDB}
    password: ${passwordDB}
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
